import { GROUND_TRUTH_DATA } from '@lucky-gazab/shared-types';

export interface ProductItem {
  id: string;
  name: string;
  slug: string;
  brand: string;
  category: string;
  subCategory?: string;
  sku: string;
  barcode?: string;
  hsnCode?: string;
  shortDescription: string;
  description: string;
  highlights: string[];
  benefits: string[];
  ingredients: string;
  usageInstructions: string;
  mrp: number;
  sellingPrice: number;
  discountPercent: number;
  isVariantParent: boolean;
  status: 'active' | 'draft' | 'inactive';
  avgRating: number;
  reviewCount: number;
  images: Array<{ url: string; altText: string; isPrimary: boolean }>;
  variants: Array<{
    id: string;
    sku: string;
    size?: string;
    color?: string;
    shade?: string;
    mrp: number;
    sellingPrice: number;
    stock: number;
  }>;
}

export const initialBrands = [
  { id: 'b1', name: "L'Oréal Professionnel", slug: 'loreal-professionnel', status: 'active' },
  { id: 'b2', name: 'Schwarzkopf Professional', slug: 'schwarzkopf-professional', status: 'active' },
  { id: 'b3', name: 'Lotus Herbals', slug: 'lotus-herbals', status: 'active' },
  { id: 'b4', name: 'O3+ Professional', slug: 'o3-professional', status: 'active' },
  { id: 'b5', name: 'Maybelline New York', slug: 'maybelline-new-york', status: 'active' },
  { id: 'b6', name: 'Streax Professional', slug: 'streax-professional', status: 'active' },
  { id: 'b7', name: 'Matrix Professional', slug: 'matrix-professional', status: 'active' },
  { id: 'b8', name: 'Vega Professional', slug: 'vega-professional', status: 'active' }
];

export const initialCategories = [
  { id: 'c1', name: 'Salon Professional Products', slug: 'salon-professional-products', parentId: null, displayOrder: 1 },
  { id: 'c2', name: 'Hair Care & Hair Color', slug: 'hair-care-hair-color', parentId: null, displayOrder: 2 },
  { id: 'c3', name: 'Skin Care & Facial Kits', slug: 'skin-care-facial-kits', parentId: null, displayOrder: 3 },
  { id: 'c4', name: 'Branded Cosmetics & Makeup', slug: 'branded-cosmetics-makeup', parentId: null, displayOrder: 4 },
  { id: 'c5', name: 'Beauty Accessories & Tools', slug: 'beauty-accessories-tools', parentId: null, displayOrder: 5 }
];

export const initialProducts: ProductItem[] = [
  // ----------------------------------------------------
  // 1. Salon Professional Products Category (10 Items)
  // ----------------------------------------------------
  {
    id: 'sp-1',
    name: "L'Oréal Professionnel X-Tenso Oleoshape Smoothing Cream",
    slug: 'loreal-xtenso-oleoshape-smoothing-cream',
    brand: "L'Oréal Professionnel",
    category: 'Salon Professional Products',
    sku: 'LOR-XTENSO-CREAM-400',
    shortDescription: 'Professional salon hair straightening and smoothing cream system.',
    description: 'Transform unruly hair into silky smooth straightened hair. Formulated with Nutri-Cationic technology for salon straightening treatments.',
    highlights: ['Nutri-Cationic Formula', 'Long-lasting salon straightening', 'Frizz control'],
    benefits: ['Smooth hair', 'Mirror shine'],
    ingredients: 'Aqua, Thioglycolic Acid, Cetearyl Alcohol, Ammonium Hydroxide.',
    usageInstructions: 'For professional salon use only with Neutralizer cream.',
    mrp: 1250,
    sellingPrice: 1099,
    discountPercent: 12,
    isVariantParent: true,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 42,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: "L'Oréal X-Tenso", isPrimary: true }],
    variants: [{ id: 'v-sp1', sku: 'LOR-XTENSO-CREAM-400', size: '400ml', mrp: 1250, sellingPrice: 1099, stock: 35 }]
  },
  {
    id: 'sp-2',
    name: 'Schwarzkopf Bonacure Keratin Smooth Perfect Treatment',
    slug: 'schwarzkopf-bonacure-keratin-smooth-treatment',
    brand: 'Schwarzkopf Professional',
    category: 'Salon Professional Products',
    sku: 'SCH-KER-SMOOTH-200',
    shortDescription: 'Deep nourishing salon treatment for frizzy, coarse hair.',
    description: 'Intensified keratin treatment that tames unruly hair and protects against humidity for 48 hours.',
    highlights: ['Keratin-infused', 'Anti-humidity barrier', 'Silky manageability'],
    benefits: ['Frizz-free smoothness', 'Heat protection'],
    ingredients: 'Aqua, Cetearyl Alcohol, Hydrolyzed Keratin, Dimethicone.',
    usageInstructions: 'Apply to wet hair, leave for 5-10 mins, rinse thoroughly.',
    mrp: 1100,
    sellingPrice: 960,
    discountPercent: 13,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 28,
    images: [{ url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80', altText: 'Schwarzkopf Keratin', isPrimary: true }],
    variants: [{ id: 'v-sp2', sku: 'SCH-KER-SMOOTH-200', size: '200ml', mrp: 1100, sellingPrice: 960, stock: 40 }]
  },
  {
    id: 'sp-3',
    name: 'Matrix Opti.Care Smooth Straight Shampoo 1000ml',
    slug: 'matrix-opticare-smooth-shampoo-1000ml',
    brand: 'Matrix Professional',
    category: 'Salon Professional Products',
    sku: 'MAT-OPTI-SHAMP-1000',
    shortDescription: 'Salon size smoothing shampoo enriched with Shea Butter.',
    description: 'Gently cleanses chemically straightened hair while maintaining smooth moisture levels.',
    highlights: ['Enriched with Shea Butter', 'Sulfate-free balance', 'Salon 1-Litre Backbar bottle'],
    benefits: ['Nourishing cleanse', 'Split end prevention'],
    ingredients: 'Aqua, Sodium Laureth Sulfate, Shea Butter, Glycol Distearate.',
    usageInstructions: 'Massage into wet scalp and hair. Rinse thoroughly.',
    mrp: 1400,
    sellingPrice: 1210,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 31,
    images: [{ url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80', altText: 'Matrix Opticare Shampoo', isPrimary: true }],
    variants: [{ id: 'v-sp3', sku: 'MAT-OPTI-SHAMP-1000', size: '1000ml', mrp: 1400, sellingPrice: 1210, stock: 25 }]
  },
  {
    id: 'sp-4',
    name: 'Lotus Herbals Professional Phyto-Rx Anti-Ageing Cream',
    slug: 'lotus-herbals-professional-phytorx-anti-ageing-cream',
    brand: 'Lotus Herbals',
    category: 'Salon Professional Products',
    sku: 'LOT-PHYTO-AGE-50',
    shortDescription: 'Professional botanical anti-ageing salon facial cream.',
    description: 'Advanced plant-derived formulation that restores collagen elasticity and reduces fine lines.',
    highlights: ['Ginseng & Ginger Extract', 'SPF 20 PA++', 'Dermatologically tested'],
    benefits: ['Wrinkle reduction', 'Firming elasticity'],
    ingredients: 'Ginseng Extract, Ginger Root Extract, Milk Protein.',
    usageInstructions: 'Apply daily after cleansing on face and neck.',
    mrp: 895,
    sellingPrice: 760,
    discountPercent: 15,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.6,
    reviewCount: 19,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'Lotus Phyto-Rx', isPrimary: true }],
    variants: [{ id: 'v-sp4', sku: 'LOT-PHYTO-AGE-50', size: '50g', mrp: 895, sellingPrice: 760, stock: 50 }]
  },
  {
    id: 'sp-5',
    name: 'Streax Professional Canvoline Hair Straightening Cream',
    slug: 'streax-professional-canvoline-straightening-cream',
    brand: 'Streax Professional',
    category: 'Salon Professional Products',
    sku: 'STR-CANV-CREAM-500',
    shortDescription: 'Salon intense hair rebonding and straightening system.',
    description: 'Enriched with Baobab Oil to protect hair fibers during permanent salon straightening.',
    highlights: ['Baobab Oil enrichment', 'Intense rebonding', 'Glossy finish'],
    benefits: ['Permanent straightening', 'Moisture locking'],
    ingredients: 'Aqua, Thioglycolate, Baobab Seed Oil, Cetyl Alcohol.',
    usageInstructions: 'For professional parlor usage with neutralizer.',
    mrp: 990,
    sellingPrice: 840,
    discountPercent: 15,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 37,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'Streax Canvoline', isPrimary: true }],
    variants: [{ id: 'v-sp5', sku: 'STR-CANV-CREAM-500', size: '500ml', mrp: 990, sellingPrice: 840, stock: 30 }]
  },
  {
    id: 'sp-6',
    name: "L'Oréal Professionnel Mythic Oil Nourishing Serum",
    slug: 'loreal-professionnel-mythic-oil-serum',
    brand: "L'Oréal Professionnel",
    category: 'Salon Professional Products',
    sku: 'LOR-MYTH-OIL-100',
    shortDescription: 'Legendary salon nourishing oil enriched with Argan Oil.',
    description: 'Provides 48-hour humidity protection and mirror shine to all hair types without weighing it down.',
    highlights: ['Argan Oil & Avocado Extract', 'Heat protection up to 230°C', 'Lightweight shine'],
    benefits: ['Instant detangling', 'Radiant shine'],
    ingredients: 'Cyclopentasiloxane, Argania Spinosa Kernel Oil, Persea Gratissima Oil.',
    usageInstructions: 'Dispense 1-2 pumps onto damp or dry hair lengths.',
    mrp: 1200,
    sellingPrice: 1050,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 65,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'Loreal Mythic Oil', isPrimary: true }],
    variants: [{ id: 'v-sp6', sku: 'LOR-MYTH-OIL-100', size: '100ml', mrp: 1200, sellingPrice: 1050, stock: 45 }]
  },
  {
    id: 'sp-7',
    name: 'Matrix Opti.Repair Liquid Protein Shampoo 350ml',
    slug: 'matrix-optirepair-liquid-protein-shampoo',
    brand: 'Matrix Professional',
    category: 'Salon Professional Products',
    sku: 'MAT-OPTI-REP-350',
    shortDescription: 'Protein repair shampoo for damaged salon-treated hair.',
    description: 'Fills porosity in damaged hair cuticles and prevents split ends caused by chemical processing.',
    highlights: ['Liquid Protein formula', 'Paraben-free', 'Cuticle smoothing'],
    benefits: ['Breakage control', 'Strength renewal'],
    ingredients: 'Aqua, Sodium Laureth Sulfate, Hydrolyzed Soy Protein.',
    usageInstructions: 'Lather into scalp and rinse with warm water.',
    mrp: 450,
    sellingPrice: 395,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 22,
    images: [{ url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80', altText: 'Matrix Opti Repair', isPrimary: true }],
    variants: [{ id: 'v-sp7', sku: 'MAT-OPTI-REP-350', size: '350ml', mrp: 450, sellingPrice: 395, stock: 55 }]
  },
  {
    id: 'sp-8',
    name: 'Schwarzkopf OSIS+ Session Extreme Hold Hairspray',
    slug: 'schwarzkopf-osis-session-extreme-hairspray',
    brand: 'Schwarzkopf Professional',
    category: 'Salon Professional Products',
    sku: 'SCH-OSIS-SESS-300',
    shortDescription: 'Ultra strong salon hold finishing hairspray.',
    description: 'Fast-drying formula providing long-lasting hold for complex salon updos and styling.',
    highlights: ['Extreme Hold level 3', 'Fast-drying non-sticky formula', 'Protects against UV rays'],
    benefits: ['All-day style hold', 'Brushable finish'],
    ingredients: 'Dimethyl Ether, Alcohol denat., Aqua, Octylacrylamide Copolymer.',
    usageInstructions: 'Spray from 30cm distance onto styled dry hair.',
    mrp: 950,
    sellingPrice: 830,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 39,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Schwarzkopf OSIS Hairspray', isPrimary: true }],
    variants: [{ id: 'v-sp8', sku: 'SCH-OSIS-SESS-300', size: '300ml', mrp: 950, sellingPrice: 830, stock: 40 }]
  },
  {
    id: 'sp-9',
    name: 'Lotus Professional Puravitals Cinnamon Cleansing Gel',
    slug: 'lotus-professional-puravitals-cinnamon-cleansing-gel',
    brand: 'Lotus Herbals',
    category: 'Salon Professional Products',
    sku: 'LOT-PURA-CINN-250',
    shortDescription: 'Purifying salon facial cleanser for oily skin.',
    description: 'Infused with Cinnamon Bark Extract to eliminate excess sebum and prevent acne breakouts.',
    highlights: ['Cinnamon & Oak Bark Extract', 'Soap-free formula', 'Deep pore cleansing'],
    benefits: ['Sebum control', 'Acne prevention'],
    ingredients: 'Cinnamon Bark Extract, Oak Bark Extract, Glycerin.',
    usageInstructions: 'Massage gently on moist face, rinse with water.',
    mrp: 475,
    sellingPrice: 410,
    discountPercent: 13,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.6,
    reviewCount: 15,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'Lotus Puravitals Cleanser', isPrimary: true }],
    variants: [{ id: 'v-sp9', sku: 'LOT-PURA-CINN-250', size: '250ml', mrp: 475, sellingPrice: 410, stock: 45 }]
  },
  {
    id: 'sp-10',
    name: 'Streax Professional Spa Nourishing Cream 500g',
    slug: 'streax-professional-spa-nourishing-cream',
    brand: 'Streax Professional',
    category: 'Salon Professional Products',
    sku: 'STR-SPA-CREAM-500',
    shortDescription: 'Deep hair spa therapy cream for dry, lifeless hair.',
    description: 'Enriched with Honey and Almond Oil to revive dull hair during salon spa treatments.',
    highlights: ['Honey & Almond Oil', 'Deep hair spa therapy', 'Silk texture'],
    benefits: ['Intense hydration', 'Softness renewal'],
    ingredients: 'Aqua, Cetearyl Alcohol, Honey, Sweet Almond Oil.',
    usageInstructions: 'Apply on damp hair post shampoo, steam for 10 mins, rinse.',
    mrp: 650,
    sellingPrice: 560,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 26,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'Streax Spa Cream', isPrimary: true }],
    variants: [{ id: 'v-sp10', sku: 'STR-SPA-CREAM-500', size: '500g', mrp: 650, sellingPrice: 560, stock: 50 }]
  },

  // ----------------------------------------------------
  // 2. Hair Care & Hair Color Category (10 Items)
  // ----------------------------------------------------
  {
    id: 'hc-1',
    name: "L'Oréal Professionnel Absolut Repair Hair Mask",
    slug: 'loreal-absolut-repair-mask',
    brand: "L'Oréal Professionnel",
    category: 'Hair Care & Hair Color',
    sku: 'LOR-ABS-MASK-250',
    shortDescription: 'Professional nourishing hair mask for damaged and dry hair.',
    description: 'Expert nourishing hair mask enriched with Gold Quinoa and Wheat Protein. Instantly restores dry, damaged hair leaving it shiny and manageable.',
    highlights: ['Gold Quinoa + Protein', '13x more damage resistance', 'Salon deep conditioning'],
    benefits: ['Deep repair', 'Shine booster', 'Frizz control'],
    ingredients: 'Aqua, Cetearyl Alcohol, Gold Quinoa Extract, Hydrolyzed Wheat Protein.',
    usageInstructions: 'Apply evenly to towel-dried hair. Leave on 3-5 mins, rinse.',
    mrp: 950,
    sellingPrice: 855,
    discountPercent: 10,
    isVariantParent: true,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 34,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: "L'Oréal Hair Mask", isPrimary: true }],
    variants: [
      { id: 'v-hc1', sku: 'LOR-ABS-MASK-250', size: '250ml', mrp: 950, sellingPrice: 855, stock: 45 },
      { id: 'v-hc1-b', sku: 'LOR-ABS-MASK-500', size: '500ml', mrp: 1650, sellingPrice: 1485, stock: 20 }
    ]
  },
  {
    id: 'hc-2',
    name: 'Schwarzkopf Igora Royal Hair Color Shade 5-0',
    slug: 'schwarzkopf-igora-royal-shade-5-0',
    brand: 'Schwarzkopf Professional',
    category: 'Hair Care & Hair Color',
    sku: 'SCH-IGORA-5-0',
    shortDescription: 'Permanent salon hair color cream with maximum coverage.',
    description: 'Schwarzkopf Igora Royal delivers 100% white hair coverage with unmatched color intensity.',
    highlights: ['100% Grey Coverage', 'Long-lasting color brilliance', 'High definition shine'],
    benefits: ['True to swatch tone', 'Luminous shine'],
    ingredients: 'Aqua, Cetearyl Alcohol, Ammonium Hydroxide.',
    usageInstructions: 'Mix 1:1 with developer. Apply for 30-45 minutes.',
    mrp: 525,
    sellingPrice: 460,
    discountPercent: 12,
    isVariantParent: true,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 18,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Schwarzkopf Igora', isPrimary: true }],
    variants: [
      { id: 'v-hc2', sku: 'SCH-IGORA-5-0', shade: '5-0 Light Brown', size: '60ml', mrp: 525, sellingPrice: 460, stock: 60 },
      { id: 'v-hc2-b', sku: 'SCH-IGORA-6-0', shade: '6-0 Dark Blonde', size: '60ml', mrp: 525, sellingPrice: 460, stock: 40 }
    ]
  },
  {
    id: 'hc-3',
    name: 'Streax Professional Argan Secret Hair Serum 100ml',
    slug: 'streax-professional-argan-secret-serum',
    brand: 'Streax Professional',
    category: 'Hair Care & Hair Color',
    sku: 'STR-ARG-SERUM-100',
    shortDescription: 'Argan oil infused shine serum for all hair types.',
    description: 'Instant frizz-free serum that tames flyaways and gives 24-hour glossy shine.',
    highlights: ['Pure Argan Oil', 'Instant detangling', 'Frizz protection'],
    benefits: ['Glossy shine', 'Silk touch'],
    ingredients: 'Cyclopentasiloxane, Argania Spinosa Kernel Oil, Vitamin E.',
    usageInstructions: 'Apply 2-3 drops to mid-lengths and ends.',
    mrp: 375,
    sellingPrice: 325,
    discountPercent: 13,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 51,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'Streax Argan Serum', isPrimary: true }],
    variants: [{ id: 'v-hc3', sku: 'STR-ARG-SERUM-100', size: '100ml', mrp: 375, sellingPrice: 325, stock: 70 }]
  },
  {
    id: 'hc-4',
    name: "L'Oréal Professionnel Majirel Hair Color Shade 3",
    slug: 'loreal-majirel-hair-color-shade-3',
    brand: "L'Oréal Professionnel",
    category: 'Hair Care & Hair Color',
    sku: 'LOR-MAJ-3-50ML',
    shortDescription: 'Classic salon permanent hair color with Ionène G.',
    description: 'Rich, deep, and intense permanent hair color with superior coverage of white hair.',
    highlights: ['Ionène G & Incell technology', 'Rich dark brown tone', 'Soft touch finish'],
    benefits: ['100% Coverage', 'Core fiber care'],
    ingredients: 'Aqua, Cetearyl Alcohol, Oleth-30, Hexadimethrine Chloride.',
    usageInstructions: 'Mix 1:1.5 with 20 vol Oxydant Cream.',
    mrp: 495,
    sellingPrice: 435,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 29,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Loreal Majirel Color', isPrimary: true }],
    variants: [{ id: 'v-hc4', sku: 'LOR-MAJ-3-50ML', shade: 'Shade 3 Dark Brown', size: '50ml', mrp: 495, sellingPrice: 435, stock: 50 }]
  },
  {
    id: 'hc-5',
    name: 'Matrix Biolage Smoothproof Leave-In Cream 100g',
    slug: 'matrix-biolage-smoothproof-leave-in-cream',
    brand: 'Matrix Professional',
    category: 'Hair Care & Hair Color',
    sku: 'MAT-BIO-SMOOTH-100',
    shortDescription: 'Camelia flower infused anti-frizz leave-in cream.',
    description: 'Controls frizz even under 97% humidity, keeping hair manageable and smooth.',
    highlights: ['Camellia Flower extract', '97% humidity resistance', 'Paraben-free'],
    benefits: ['Humidity barrier', 'Soft touch'],
    ingredients: 'Aqua, Cetearyl Alcohol, Camellia Oleifera Seed Oil.',
    usageInstructions: 'Apply through damp hair from roots to ends. Do not rinse.',
    mrp: 400,
    sellingPrice: 350,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 23,
    images: [{ url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80', altText: 'Matrix Biolage', isPrimary: true }],
    variants: [{ id: 'v-hc5', sku: 'MAT-BIO-SMOOTH-100', size: '100g', mrp: 400, sellingPrice: 350, stock: 45 }]
  },
  {
    id: 'hc-6',
    name: 'Schwarzkopf Bonacure Color Freeze Silver Shampoo',
    slug: 'schwarzkopf-bonacure-color-freeze-silver-shampoo',
    brand: 'Schwarzkopf Professional',
    category: 'Hair Care & Hair Color',
    sku: 'SCH-SILVER-SHAMP-250',
    shortDescription: 'Neutralizing shampoo for blonde and grey colored hair.',
    description: 'Cell Equalizer technology neutralizes unwanted brassy tones in color-treated blonde hair.',
    highlights: ['pH 4.5 balancer', 'Anti-yellow pigments', 'Vegan keratine'],
    benefits: ['Color retention', 'Brassy tone removal'],
    ingredients: 'Aqua, Cocamidopropyl Betaine, Acid Violet 43.',
    usageInstructions: 'Apply to wet hair, leave 2-5 mins, rinse thoroughly.',
    mrp: 1050,
    sellingPrice: 920,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 33,
    images: [{ url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80', altText: 'Schwarzkopf Silver Shampoo', isPrimary: true }],
    variants: [{ id: 'v-hc6', sku: 'SCH-SILVER-SHAMP-250', size: '250ml', mrp: 1050, sellingPrice: 920, stock: 30 }]
  },
  {
    id: 'hc-7',
    name: "L'Oréal Professionnel Serie Expert Inforcer Mask",
    slug: 'loreal-serie-expert-inforcer-mask',
    brand: "L'Oréal Professionnel",
    category: 'Hair Care & Hair Color',
    sku: 'LOR-INF-MASK-250',
    shortDescription: 'Anti-breakage mask infused with Vitamin B6 and Biotin.',
    description: 'Deeply strengthens fragile, thinning hair to minimize split ends and breakage.',
    highlights: ['Biotin + Vitamin B6', 'Anti-breakage action', 'Hair density booster'],
    benefits: ['Breakage reduction', 'Fiber resilience'],
    ingredients: 'Aqua, Cetearyl Alcohol, Pyridoxine HCl, Biotin.',
    usageInstructions: 'Apply on shampooed hair, leave 3-5 mins, rinse.',
    mrp: 950,
    sellingPrice: 855,
    discountPercent: 10,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 20,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'Loreal Inforcer Mask', isPrimary: true }],
    variants: [{ id: 'v-hc7', sku: 'LOR-INF-MASK-250', size: '250ml', mrp: 950, sellingPrice: 855, stock: 35 }]
  },
  {
    id: 'hc-8',
    name: 'Matrix Opti.Care Intense Smoothing Mask 200g',
    slug: 'matrix-opticare-intense-smoothing-mask',
    brand: 'Matrix Professional',
    category: 'Hair Care & Hair Color',
    sku: 'MAT-OPTI-MASK-200',
    shortDescription: 'Intense conditioner for straightened and frizzy hair.',
    description: 'Nourishes dry cuticle layers to keep hair straight and manageable.',
    highlights: ['Shea Butter nourishment', 'Frizz locking', 'Silky feel'],
    benefits: ['Smooth hair', 'Moisture balance'],
    ingredients: 'Aqua, Cetearyl Alcohol, Shea Butter, Behentrimonium Chloride.',
    usageInstructions: 'Use weekly after shampooing, rinse well.',
    mrp: 525,
    sellingPrice: 460,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 17,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'Matrix Opticare Mask', isPrimary: true }],
    variants: [{ id: 'v-hc8', sku: 'MAT-OPTI-MASK-200', size: '200g', mrp: 525, sellingPrice: 460, stock: 40 }]
  },
  {
    id: 'hc-9',
    name: 'Schwarzkopf OSIS+ Magic Anti-Frizz Shine Serum',
    slug: 'schwarzkopf-osis-magic-shine-serum',
    brand: 'Schwarzkopf Professional',
    category: 'Hair Care & Hair Color',
    sku: 'SCH-OSIS-MAG-50',
    shortDescription: 'Weightless shine serum for smooth silky texture.',
    description: 'Instant gloss finish that separates strands and prevents flyaway frizz.',
    highlights: ['Silicones & Glycerin', 'Weightless shine', 'Instantly wash out'],
    benefits: ['High gloss', 'Flyaway taming'],
    ingredients: 'Aqua, Dimethicone, Glycerin, Phenoxyethanol.',
    usageInstructions: 'Apply small amount to dry or damp hair.',
    mrp: 1000,
    sellingPrice: 875,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 25,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'Schwarzkopf OSIS Magic', isPrimary: true }],
    variants: [{ id: 'v-hc9', sku: 'SCH-OSIS-MAG-50', size: '50ml', mrp: 1000, sellingPrice: 875, stock: 30 }]
  },
  {
    id: 'hc-10',
    name: 'Streax Professional Spa Hair Straightening Kit',
    slug: 'streax-professional-spa-straightening-kit',
    brand: 'Streax Professional',
    category: 'Hair Care & Hair Color',
    sku: 'STR-SPA-KIT-200',
    shortDescription: 'Home salon hair spa treatment kit.',
    description: 'Includes smoothing shampoo, spa mask, and serum for home hair care.',
    highlights: ['3-Step Hair Spa Kit', 'Organic Coconut Oil', 'Salon touch'],
    benefits: ['Total hair revival', 'Gloss finish'],
    ingredients: 'Coconut Oil, Keratin, Silk Amino Acids.',
    usageInstructions: 'Follow 3-step guide: Wash -> Mask -> Serum.',
    mrp: 699,
    sellingPrice: 599,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.6,
    reviewCount: 14,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'Streax Spa Kit', isPrimary: true }],
    variants: [{ id: 'v-hc10', sku: 'STR-SPA-KIT-200', size: 'Combo Pack', mrp: 699, sellingPrice: 599, stock: 35 }]
  },

  // ----------------------------------------------------
  // 3. Skin Care & Facial Kits Category (10 Items)
  // ----------------------------------------------------
  {
    id: 'sc-1',
    name: 'O3+ Professional Brightening Facial Kit',
    slug: 'o3-professional-brightening-facial-kit',
    brand: 'O3+ Professional',
    category: 'Skin Care & Facial Kits',
    sku: 'O3-BRIGHT-FACIAL-KIT',
    shortDescription: 'Dermatologist tested salon professional facial kit for glowing skin.',
    description: 'Award-winning O3+ facial treatment kit designed for salon professionals and bridal radiance.',
    highlights: ['Reduces pigmentation', 'Instant glow effect', 'Hygiene packed pods'],
    benefits: ['Even skin tone', 'Radiant glow'],
    ingredients: 'Vitamin C, Niacinamide, Milk Protein, Licorice Extract.',
    usageInstructions: 'Follow 5-step process: Cleanser -> Scrub -> Cream -> Peel Off Mask -> Serum.',
    mrp: 1450,
    sellingPrice: 1290,
    discountPercent: 11,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 52,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'O3+ Facial Kit', isPrimary: true }],
    variants: [{ id: 'v-sc1', sku: 'O3-BRIGHT-FACIAL-KIT', size: 'Single Pack (125g)', mrp: 1450, sellingPrice: 1290, stock: 30 }]
  },
  {
    id: 'sc-2',
    name: 'Lotus Herbals Safe Sun UV Screen Matte GEL SPF 50',
    slug: 'lotus-herbals-safe-sun-matte-gel-spf-50',
    brand: 'Lotus Herbals',
    category: 'Skin Care & Facial Kits',
    sku: 'LOT-SUN-SPF50-100',
    shortDescription: 'Ultra-lightweight oil-free matte sunscreen gel.',
    description: 'Protects against UVA & UVB rays while controlling shine and oil for up to 8 hours.',
    highlights: ['SPF 50 PA+++', 'Non-greasy Matte Gel', 'Sweat & water resistant'],
    benefits: ['Sunburn protection', 'Oil control'],
    ingredients: 'Horse Chestnut, Comfrey, Vanilla extract, Octyl Methoxycinnamate.',
    usageInstructions: 'Apply liberally 15 mins before sun exposure.',
    mrp: 495,
    sellingPrice: 425,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 88,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'Lotus Sunscreen Gel', isPrimary: true }],
    variants: [{ id: 'v-sc2', sku: 'LOT-SUN-SPF50-100', size: '100g', mrp: 495, sellingPrice: 425, stock: 80 }]
  },
  {
    id: 'sc-3',
    name: 'O3+ Derma Glow Facial Treatment Pods',
    slug: 'o3-derma-glow-facial-treatment-pods',
    brand: 'O3+ Professional',
    category: 'Skin Care & Facial Kits',
    sku: 'O3-DERMA-GLOW-PODS',
    shortDescription: 'Advanced dermaceutical skin brightening pods.',
    description: 'Clinical grade facial treatment pods enriched with Arbutin and Hyaluronic acid.',
    highlights: ['Hyaluronic Acid + Arbutin', 'Dermatologist formulation', 'Pigmentation control'],
    benefits: ['Hydration surge', 'Skin clarification'],
    ingredients: 'Hyaluronic Acid, Alpha Arbutin, Glycolic Acid.',
    usageInstructions: 'Use pod steps in sequence for professional facial.',
    mrp: 1850,
    sellingPrice: 1650,
    discountPercent: 10,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 35,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'O3+ Derma Pods', isPrimary: true }],
    variants: [{ id: 'v-sc3', sku: 'O3-DERMA-GLOW-PODS', size: 'Pack of 6 Pods', mrp: 1850, sellingPrice: 1650, stock: 25 }]
  },
  {
    id: 'sc-4',
    name: 'Lotus Herbals WhiteGlow Skin Whitening Gel Crème SPF 25',
    slug: 'lotus-herbals-whiteglow-skin-whitening-gel-creme',
    brand: 'Lotus Herbals',
    category: 'Skin Care & Facial Kits',
    sku: 'LOT-WHITEGLOW-60G',
    shortDescription: 'Lightweight day cream for luminous fair skin tone.',
    description: 'Blends the freshness of gel with the nourishment of cream to reduce melanin production.',
    highlights: ['Grape & Mulberry Extract', 'SPF 25 PA+++', 'Non-sticky texture'],
    benefits: ['Fair skin tone', 'UV protection'],
    ingredients: 'Grape Extract, Mulberry Extract, Saxifraga Extract.',
    usageInstructions: 'Apply smoothly onto cleansed face every morning.',
    mrp: 425,
    sellingPrice: 365,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 64,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'Lotus Whiteglow', isPrimary: true }],
    variants: [{ id: 'v-sc4', sku: 'LOT-WHITEGLOW-60G', size: '60g', mrp: 425, sellingPrice: 365, stock: 65 }]
  },
  {
    id: 'sc-5',
    name: 'O3+ Seaweed Facial Kit for Acne Prone Skin',
    slug: 'o3-seaweed-facial-kit-acne-prone-skin',
    brand: 'O3+ Professional',
    category: 'Skin Care & Facial Kits',
    sku: 'O3-SEAWEED-KIT-125G',
    shortDescription: 'Soothing facial kit designed to calm breakouts and control sebum.',
    description: 'Enriched with natural marine seaweed extracts to purify pores and eliminate acne bacteria.',
    highlights: ['Marine Seaweed Extract', 'Acne calming formula', 'Reduces excess oil'],
    benefits: ['Pore purification', 'Acne control'],
    ingredients: 'Seaweed Extract, Tea Tree Oil, Willow Bark Extract.',
    usageInstructions: 'Follow 4-step facial treatment.',
    mrp: 1550,
    sellingPrice: 1380,
    discountPercent: 11,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 22,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'O3+ Seaweed Kit', isPrimary: true }],
    variants: [{ id: 'v-sc5', sku: 'O3-SEAWEED-KIT-125G', size: 'Single Pack (125g)', mrp: 1550, sellingPrice: 1380, stock: 20 }]
  },
  {
    id: 'sc-6',
    name: 'O3+ Whitening D-Tan Pack 300g Jar',
    slug: 'o3-whitening-dtan-pack-300g',
    brand: 'O3+ Professional',
    category: 'Skin Care & Facial Kits',
    sku: 'O3-DTAN-PACK-300G',
    shortDescription: 'Instant sun tan removal pack enriched with Mint and Eucalyptus.',
    description: 'Professional salon D-Tan pack that lifts sun darkening and brightens face and body skin instantly.',
    highlights: ['Eucalyptus & Mint extracts', 'Instant tan removal', 'Paraben-free'],
    benefits: ['Tan removal', 'Instant cooling'],
    ingredients: 'Mint, Eucalyptus Oil, Clove Oil, Kaolin Clay.',
    usageInstructions: 'Apply thin layer on face/body, leave 10 mins, wipe off.',
    mrp: 1350,
    sellingPrice: 1190,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 95,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'O3+ D-Tan Pack', isPrimary: true }],
    variants: [{ id: 'v-sc6', sku: 'O3-DTAN-PACK-300G', size: '300g Jar', mrp: 1350, sellingPrice: 1190, stock: 40 }]
  },
  {
    id: 'sc-7',
    name: 'Lotus Herbals Radiant Gold Cellular Glow Facial Kit',
    slug: 'lotus-herbals-radiant-gold-facial-kit',
    brand: 'Lotus Herbals',
    category: 'Skin Care & Facial Kits',
    sku: 'LOT-GOLD-FACIAL-170G',
    shortDescription: 'Gold leaves infused cellular glow facial kit for brides.',
    description: 'Enriched with 24K Gold Leaves and Papaya extract for instant bridal radiance.',
    highlights: ['24K Gold Leaf Particles', 'Deep cellular activation', 'Instant parlor glow'],
    benefits: ['Gold radiance', 'Cellular repair'],
    ingredients: '24K Gold Leaves, Papaya Extract, Horse Chestnut.',
    usageInstructions: 'Use 4-step kit: Exfoliator -> Activator -> Massage Cream -> Mask.',
    mrp: 1250,
    sellingPrice: 1050,
    discountPercent: 16,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 38,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'Lotus Gold Facial', isPrimary: true }],
    variants: [{ id: 'v-sc7', sku: 'LOT-GOLD-FACIAL-170G', size: '170g Kit', mrp: 1250, sellingPrice: 1050, stock: 35 }]
  },
  {
    id: 'sc-8',
    name: 'O3+ Oxygenating D-Tan Facial Mask 100g',
    slug: 'o3-oxygenating-dtan-facial-mask',
    brand: 'O3+ Professional',
    category: 'Skin Care & Facial Kits',
    sku: 'O3-OXY-DTAN-100G',
    shortDescription: 'Oxygenating peel-off mask for luminous skin texture.',
    description: 'Infuses active oxygen molecules into skin cells to purge impurities and dullness.',
    highlights: ['Active Oxygen infusion', 'Peel-off formulation', 'Deep brightening'],
    benefits: ['Detoxification', 'Radiant skin'],
    ingredients: 'Oxygen Complex, Botanical Peptides, Marine Algae.',
    usageInstructions: 'Apply layer, allow to dry 15 mins, peel off gently.',
    mrp: 850,
    sellingPrice: 750,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 29,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'O3+ Oxygen Mask', isPrimary: true }],
    variants: [{ id: 'v-sc8', sku: 'O3-OXY-DTAN-100G', size: '100g Tube', mrp: 850, sellingPrice: 750, stock: 30 }]
  },
  {
    id: 'sc-9',
    name: 'Lotus Herbals YouthRx Anti-Ageing Transforming Crème',
    slug: 'lotus-herbals-youthrx-anti-ageing-creme',
    brand: 'Lotus Herbals',
    category: 'Skin Care & Facial Kits',
    sku: 'LOT-YOUTHRX-CREME-50G',
    shortDescription: 'Gineplex Youth Compound firming night crème.',
    description: 'Accelerates skin cell renewal during sleep to firm skin texture and reduce dark circles.',
    highlights: ['Gineplex Youth Compound', 'Visible wrinkle reduction in 10 days', 'Night treatment'],
    benefits: ['Firming lift', 'Cellular renewal'],
    ingredients: 'Ginseng, Ginger, Milk Peptides.',
    usageInstructions: 'Massage gently onto clean face before bed.',
    mrp: 795,
    sellingPrice: 680,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.6,
    reviewCount: 18,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'Lotus YouthRx Crème', isPrimary: true }],
    variants: [{ id: 'v-sc9', sku: 'LOT-YOUTHRX-CREME-50G', size: '50g Jar', mrp: 795, sellingPrice: 680, stock: 40 }]
  },
  {
    id: 'sc-10',
    name: 'O3+ Vitamin C Glow Sheet Mask (Pack of 5)',
    slug: 'o3-vitamin-c-glow-sheet-mask-pack',
    brand: 'O3+ Professional',
    category: 'Skin Care & Facial Kits',
    sku: 'O3-VITC-SHEET-5PK',
    shortDescription: 'Hydrating Vitamin C concentrated facial sheet masks.',
    description: 'Provides 24-hour hydration surge and skin illumination in just 15 minutes.',
    highlights: ['Concentrated Vitamin C Serum', 'Biodegradable sheet fiber', 'Dermatologist approved'],
    benefits: ['Hydration surge', 'Instant illumination'],
    ingredients: 'Vitamin C, Hyaluronic Acid, Orange Peel Extract.',
    usageInstructions: 'Unfold sheet mask, place on face for 15 mins, massage remaining serum.',
    mrp: 750,
    sellingPrice: 650,
    discountPercent: 13,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 45,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'O3+ Vitamin C Sheet Mask', isPrimary: true }],
    variants: [{ id: 'v-sc10', sku: 'O3-VITC-SHEET-5PK', size: 'Pack of 5 Sheets', mrp: 750, sellingPrice: 650, stock: 50 }]
  },

  // ----------------------------------------------------
  // 4. Branded Cosmetics & Makeup Category (10 Items)
  // ----------------------------------------------------
  {
    id: 'cm-1',
    name: 'Maybelline Superstay Matte Ink Liquid Lipstick',
    slug: 'maybelline-superstay-matte-ink',
    brand: 'Maybelline New York',
    category: 'Branded Cosmetics & Makeup',
    sku: 'MAY-MATTE-INK-RULER',
    shortDescription: '16-hour long lasting transfer-proof liquid lipstick.',
    description: 'Ink your lips in up to 16 hours of saturated liquid matte color.',
    highlights: ['Up to 16 Hour Wear', 'Transfer-proof formula', 'Arrow applicator tip'],
    benefits: ['Non-drying formula', 'Bold color payoff'],
    ingredients: 'Dimethicone, Isododecane, Trimethylsiloxysilicate.',
    usageInstructions: 'Apply in center of upper lip and follow contours.',
    mrp: 699,
    sellingPrice: 599,
    discountPercent: 14,
    isVariantParent: true,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 89,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Maybelline Liquid Lipstick', isPrimary: true }],
    variants: [
      { id: 'v-cm1', sku: 'MAY-MATTE-INK-RULER', shade: '80 Ruler', size: '5ml', mrp: 699, sellingPrice: 599, stock: 50 },
      { id: 'v-cm1-b', sku: 'MAY-MATTE-INK-PIONEER', shade: '20 Pioneer', size: '5ml', mrp: 699, sellingPrice: 599, stock: 45 }
    ]
  },
  {
    id: 'cm-2',
    name: 'Maybelline Fit Me Matte + Poreless Liquid Foundation',
    slug: 'maybelline-fit-me-matte-poreless-foundation',
    brand: 'Maybelline New York',
    category: 'Branded Cosmetics & Makeup',
    sku: 'MAY-FITME-FOUND-128',
    shortDescription: 'Natural matte finish liquid foundation with clay technology.',
    description: 'Refines pores and absorbs oil for a natural, seamless matte finish.',
    highlights: ['Clay tech oil control', 'SPF 22 PA+++', 'Non-comedogenic'],
    benefits: ['Pore refinement', 'Natural coverage'],
    ingredients: 'Aqua, Cyclohexasiloxane, Nylon-12, Isododecane.',
    usageInstructions: 'Apply evenly to face and blend with fingertips or sponge.',
    mrp: 649,
    sellingPrice: 550,
    discountPercent: 15,
    isVariantParent: true,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 110,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Maybelline Fit Me Foundation', isPrimary: true }],
    variants: [
      { id: 'v-cm2', sku: 'MAY-FITME-FOUND-128', shade: '128 Warm Nude', size: '30ml', mrp: 649, sellingPrice: 550, stock: 60 },
      { id: 'v-cm2-b', sku: 'MAY-FITME-FOUND-220', shade: '220 Natural Beige', size: '30ml', mrp: 649, sellingPrice: 550, stock: 50 }
    ]
  },
  {
    id: 'cm-3',
    name: 'Maybelline Colossal Waterproof Mascara 10ml',
    slug: 'maybelline-colossal-waterproof-mascara',
    brand: 'Maybelline New York',
    category: 'Branded Cosmetics & Makeup',
    sku: 'MAY-COLOSSAL-MASC-10ML',
    shortDescription: 'Volume boosting waterproof mascara with mega brush.',
    description: 'Delivers 2x colossal volume to lashes without clumping. Waterproof collagen formula.',
    highlights: ['Mega brush applicator', '2x Volume boost', '24H Waterproof'],
    benefits: ['Zero clump volume', 'Intense black pigment'],
    ingredients: 'Isododecane, Cera Alba, Collagen, Paraffin.',
    usageInstructions: 'Sweep mega brush from lash root to tip.',
    mrp: 449,
    sellingPrice: 385,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 75,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Maybelline Colossal Mascara', isPrimary: true }],
    variants: [{ id: 'v-cm3', sku: 'MAY-COLOSSAL-MASC-10ML', color: 'Glam Black', size: '10ml', mrp: 449, sellingPrice: 385, stock: 70 }]
  },
  {
    id: 'cm-4',
    name: "L'Oréal Paris Infallible 24H Fresh Wear Powder Foundation",
    slug: 'loreal-paris-infallible-24h-powder-foundation',
    brand: "L'Oréal Professionnel",
    category: 'Branded Cosmetics & Makeup',
    sku: 'LOR-INF-POWDER-120',
    shortDescription: '24-hour full coverage weightless powder foundation.',
    description: 'Covers like a liquid foundation while mattifying like a powder. Waterproof and sweat-proof.',
    highlights: ['24H Full Coverage', 'Waterproof & Transfer-proof', 'Matte finish'],
    benefits: ['All day wear', 'Seamless coverage'],
    ingredients: 'Talc, Zinc Stearate, Dimethicone, Silica.',
    usageInstructions: 'Apply with enclosed sponge or powder brush.',
    mrp: 1099,
    sellingPrice: 950,
    discountPercent: 13,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 42,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Loreal Powder Foundation', isPrimary: true }],
    variants: [{ id: 'v-cm4', sku: 'LOR-INF-POWDER-120', shade: '120 Vanilla', size: '9g', mrp: 1099, sellingPrice: 950, stock: 40 }]
  },
  {
    id: 'cm-5',
    name: 'Maybelline Instant Age Rewind Eraser Concealer',
    slug: 'maybelline-instant-age-rewind-eraser-concealer',
    brand: 'Maybelline New York',
    category: 'Branded Cosmetics & Makeup',
    sku: 'MAY-AGE-REWIND-MEDIUM',
    shortDescription: 'Dark circles treatment concealer with micro-corrector sponge.',
    description: 'Erases dark circles, puffiness, and fine lines instantly for a refreshed look.',
    highlights: ['Micro-corrector sponge', 'Goji berry & Haloxyl infused', 'Medium coverage'],
    benefits: ['Dark circle erasing', 'Hydrating treatment'],
    ingredients: 'Aqua, Cyclopentasiloxane, Haloxyl, Goji Berry Extract.',
    usageInstructions: 'Turn collar of applicator until formula appears on sponge. Apply to under-eye.',
    mrp: 720,
    sellingPrice: 620,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 98,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Maybelline Age Rewind', isPrimary: true }],
    variants: [{ id: 'v-cm5', sku: 'MAY-AGE-REWIND-MEDIUM', shade: 'Medium 130', size: '6ml', mrp: 720, sellingPrice: 620, stock: 55 }]
  },
  {
    id: 'cm-6',
    name: "L'Oréal Paris Color Riche Intense Volume Matte Lipstick",
    slug: 'loreal-color-riche-intense-volume-matte-lipstick',
    brand: "L'Oréal Professionnel",
    category: 'Branded Cosmetics & Makeup',
    sku: 'LOR-COLOR-RICHE-601',
    shortDescription: '16-hour powdery matte lipstick infused with Hyaluronic Acid.',
    description: 'Plumps lips with powdery velvet matte color and intense hydrating comfort.',
    highlights: ['Hyaluronic Acid infused', 'Powdery velvet matte finish', 'Slim bullet design'],
    benefits: ['Lip plumping hydration', '16H wear'],
    ingredients: 'Dimethicone, Isododecane, Sodium Hyaluronate.',
    usageInstructions: 'Apply starting from Cupid’s bow towards corners.',
    mrp: 799,
    sellingPrice: 699,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 36,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Loreal Color Riche Lipstick', isPrimary: true }],
    variants: [{ id: 'v-cm6', sku: 'LOR-COLOR-RICHE-601', shade: '601 Worth It Nude', size: '1.8g', mrp: 799, sellingPrice: 699, stock: 45 }]
  },
  {
    id: 'cm-7',
    name: 'Maybelline Master Chrome Metallic Highlighter',
    slug: 'maybelline-master-chrome-metallic-highlighter',
    brand: 'Maybelline New York',
    category: 'Branded Cosmetics & Makeup',
    sku: 'MAY-MASTER-CHROME-MOLTEN',
    shortDescription: 'High-impact metallic sheen compact highlighter.',
    description: 'Melts into skin for a molten metal glow highlighting cheekbones and brow bones.',
    highlights: ['Pearlescent pigments', 'Reflective chrome sheen', 'Smooth powder blend'],
    benefits: ['Molten metal glow', 'Buildable intensity'],
    ingredients: 'Caprylic/Capric Triglyceride, Bis-Diglyceryl Polyacyladipate-2, Mica.',
    usageInstructions: 'Sweep with highlighter brush onto high points of face.',
    mrp: 650,
    sellingPrice: 560,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 54,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Maybelline Master Chrome', isPrimary: true }],
    variants: [{ id: 'v-cm7', sku: 'MAY-MASTER-CHROME-MOLTEN', shade: 'Molten Gold 100', size: '6.7g', mrp: 650, sellingPrice: 560, stock: 35 }]
  },
  {
    id: 'cm-8',
    name: "L'Oréal Paris Lash Paradise Waterproof Mascara",
    slug: 'loreal-lash-paradise-waterproof-mascara',
    brand: "L'Oréal Professionnel",
    category: 'Branded Cosmetics & Makeup',
    sku: 'LOR-LASH-PARADISE-9ML',
    shortDescription: 'Volumizing & lengthening mascara with soft wavy brush.',
    description: 'Delivers intense volume and breathtaking length with feather-soft wavy brush fibers.',
    highlights: ['Wavy bristle brush', 'Floral oil enrichment', '24H Waterproof'],
    benefits: ['Voluptuous volume', 'Soft lash feel'],
    ingredients: 'Isododecane, Beeswax, Corn Starch, Ricinus Communis Seed Oil.',
    usageInstructions: 'Wiggle brush from base of lashes to tip.',
    mrp: 899,
    sellingPrice: 780,
    discountPercent: 13,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 48,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Loreal Lash Paradise', isPrimary: true }],
    variants: [{ id: 'v-cm8', sku: 'LOR-LASH-PARADISE-9ML', color: 'Blackest Black', size: '9ml', mrp: 899, sellingPrice: 780, stock: 50 }]
  },
  {
    id: 'cm-9',
    name: 'Maybelline Hyper Glossy Liquid Eyeliner Black 3g',
    slug: 'maybelline-hyper-glossy-liquid-eyeliner',
    brand: 'Maybelline New York',
    category: 'Branded Cosmetics & Makeup',
    sku: 'MAY-HYPER-GLOSS-BLACK',
    shortDescription: '24-hour high shine vinyl liquid eyeliner.',
    description: 'Delivers intense glossy black lines with a flexible precision tip applicator.',
    highlights: ['24H Glossy finish', 'Smudge-proof & water-resistant', 'Flexible tip'],
    benefits: ['High vinyl shine', 'Precision wing design'],
    ingredients: 'Aqua, Styrene/Acrylates Copolymer, Propylene Glycol.',
    usageInstructions: 'Draw line along upper lash line starting from inner corner.',
    mrp: 349,
    sellingPrice: 295,
    discountPercent: 15,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 82,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Maybelline Hyper Glossy Eyeliner', isPrimary: true }],
    variants: [{ id: 'v-cm9', sku: 'MAY-HYPER-GLOSS-BLACK', color: 'Glossy Black', size: '3g', mrp: 349, sellingPrice: 295, stock: 75 }]
  },
  {
    id: 'cm-10',
    name: 'Maybelline Baby Lips Pink Bloom Lip Balm 4.5g',
    slug: 'maybelline-baby-lips-pink-bloom-balm',
    brand: 'Maybelline New York',
    category: 'Branded Cosmetics & Makeup',
    sku: 'MAY-BABY-LIPS-PINK',
    shortDescription: 'Color transforming moisturizing lip balm with SPF 16.',
    description: 'Transforms from clear balm into a custom flush of pink tint on contact with lips.',
    highlights: ['Color changing technology', '12H Moisture surge', 'SPF 16 sun protection'],
    benefits: ['Custom pink tint', 'Hydrated lips'],
    ingredients: 'Polybutene, Octyldodecanol, Jojoba Seed Oil, Tocopherol.',
    usageInstructions: 'Apply liberally to lips whenever dry.',
    mrp: 210,
    sellingPrice: 180,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 60,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Maybelline Baby Lips', isPrimary: true }],
    variants: [{ id: 'v-cm10', sku: 'MAY-BABY-LIPS-PINK', shade: 'Pink Bloom', size: '4.5g', mrp: 210, sellingPrice: 180, stock: 90 }]
  },

  // ----------------------------------------------------
  // 5. Beauty Accessories & Tools Category (3 Items)
  // ----------------------------------------------------
  {
    id: 'ba-1',
    name: 'Vega Professional Pro Touch Hair Dryer 2000W',
    slug: 'vega-professional-pro-touch-hair-dryer',
    brand: 'Vega Professional',
    category: 'Beauty Accessories & Tools',
    sku: 'VEG-PRO-DRYER-2000W',
    shortDescription: 'Salon 2000W AC motor professional hair dryer with cool shot.',
    description: 'Delivers high airflow velocity for fast blowout drying in professional parlors.',
    highlights: ['2000W Heavy Duty AC Motor', 'Cool Shot Button', '2 Nozzles included'],
    benefits: ['Fast blowout drying', 'Frizz reduction'],
    ingredients: 'Ceramic heating element, Nylon housing.',
    usageInstructions: 'Use concentrator nozzle for blowout styling.',
    mrp: 2990,
    sellingPrice: 2490,
    discountPercent: 17,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 30,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Vega Pro Hair Dryer', isPrimary: true }],
    variants: [{ id: 'v-ba1', sku: 'VEG-PRO-DRYER-2000W', size: '2000W Unit', mrp: 2990, sellingPrice: 2490, stock: 20 }]
  },
  {
    id: 'ba-2',
    name: 'Vega Professional Ceramic Hair Straightening Iron',
    slug: 'vega-professional-ceramic-hair-straightener',
    brand: 'Vega Professional',
    category: 'Beauty Accessories & Tools',
    sku: 'VEG-CERAMIC-STRAIGHT-230',
    shortDescription: 'Floating ceramic plates hair straightener up to 230°C.',
    description: 'Rapid 60-second heat up straightener with digital temperature controller for salon styling.',
    highlights: ['Ceramic Coated Plates', 'Variable Temp 130°C - 230°C', 'Auto 60m shut-off'],
    benefits: ['Smooth glide', 'Zero hair snagging'],
    ingredients: 'Ceramic plates, PTC heater.',
    usageInstructions: 'Glide iron down small sections of dry hair.',
    mrp: 2850,
    sellingPrice: 2350,
    discountPercent: 18,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 26,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Vega Hair Straightener', isPrimary: true }],
    variants: [{ id: 'v-ba2', sku: 'VEG-CERAMIC-STRAIGHT-230', size: '1-Inch Plates', mrp: 2850, sellingPrice: 2350, stock: 25 }]
  },
  {
    id: 'ba-3',
    name: 'Vega Pro Salon Blending Sponge Set (Pack of 3)',
    slug: 'vega-pro-salon-blending-sponge-set',
    brand: 'Vega Professional',
    category: 'Beauty Accessories & Tools',
    sku: 'VEG-SPONGE-3PK',
    shortDescription: 'Precision teardrop foundation blending sponges.',
    description: 'Latex-free precision beauty sponges for streak-free liquid foundation and concealer blending.',
    highlights: ['Latex-Free Hydrophilic Sponge', 'Expands 2x when wet', 'Streak-free blending'],
    benefits: ['Seamless foundation application', 'Minimal product absorption'],
    ingredients: 'Hydrophilic Polyurethane.',
    usageInstructions: 'Wet sponge, squeeze excess water, bounce onto face.',
    mrp: 499,
    sellingPrice: 399,
    discountPercent: 20,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 40,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Vega Blending Sponges', isPrimary: true }],
    variants: [{ id: 'v-ba3', sku: 'VEG-SPONGE-3PK', size: 'Pack of 3', mrp: 499, sellingPrice: 399, stock: 60 }]
  }
];

export const initialBanners = [
  {
    id: 'ban-1',
    title: 'Salon Professional Range Sale — Up to 30% OFF',
    imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1600&q=80',
    linkUrl: '/products?category=salon-professional-products',
    position: 'hero',
    displayOrder: 1,
    status: 'active'
  },
  {
    id: 'ban-2',
    title: 'Branded Cosmetics & Hair Care Specials in Indore',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1600&q=80',
    linkUrl: '/products?category=hair-care-hair-color',
    position: 'hero',
    displayOrder: 2,
    status: 'active'
  }
];

export const initialCoupons = [
  {
    id: 'coup-1',
    code: 'GAZAB10',
    type: 'percentage',
    value: 10,
    minCartValue: 999,
    maxDiscount: 300,
    usageLimitTotal: 500,
    usageLimitPerCustomer: 1,
    status: 'active'
  },
  {
    id: 'coup-2',
    code: 'WELCOME200',
    type: 'flat',
    value: 200,
    minCartValue: 1499,
    usageLimitTotal: 200,
    usageLimitPerCustomer: 1,
    status: 'active'
  }
];
