import { GROUND_TRUTH_DATA } from '@lucky-gazab/shared-types';

export interface ProductItem {
  id: string;
  name: string;
  slug: string;
  brand: string;
  category: string;
  subCategory?: string;
  sku: string;
  barcode?: string;
  hsnCode?: string;
  shortDescription: string;
  description: string;
  highlights: string[];
  benefits: string[];
  ingredients: string;
  usageInstructions: string;
  mrp: number;
  sellingPrice: number;
  discountPercent: number;
  isVariantParent: boolean;
  status: 'active' | 'draft' | 'inactive';
  avgRating: number;
  reviewCount: number;
  isFeatured?: boolean;
  isBestseller?: boolean;
  images: Array<{ url: string; altText: string; isPrimary: boolean }>;
  variants: Array<{
    id: string;
    sku: string;
    size?: string;
    color?: string;
    shade?: string;
    mrp: number;
    sellingPrice: number;
    stock: number;
  }>;
}

export const initialBrands = [
  { id: 'b1', name: "L'Oréal Professionnel", slug: 'loreal-professionnel', status: 'active' },
  { id: 'b2', name: 'Schwarzkopf Professional', slug: 'schwarzkopf-professional', status: 'active' },
  { id: 'b3', name: 'Matrix Professional', slug: 'matrix-professional', status: 'active' },
  { id: 'b4', name: 'Wella Professionals', slug: 'wella-professionals', status: 'active' },
  { id: 'b5', name: 'Streax Professional', slug: 'streax-professional', status: 'active' },
  { id: 'b6', name: 'GK Hair', slug: 'gk-hair', status: 'active' },
  { id: 'b7', name: 'Olaplex', slug: 'olaplex', status: 'active' },
  { id: 'b8', name: 'O3+ Professional', slug: 'o3-professional', status: 'active' },
  { id: 'b9', name: 'Maybelline New York', slug: 'maybelline-new-york', status: 'active' },
  { id: 'b10', name: 'Lakmé Cosmetics', slug: 'lakme-cosmetics', status: 'active' },
  { id: 'b11', name: 'Mamaearth', slug: 'mamaearth', status: 'active' },
  { id: 'b12', name: 'Minimalist', slug: 'minimalist', status: 'active' },
  { id: 'b13', name: 'Dot & Key Skincare', slug: 'dot-and-key-skincare', status: 'active' },
  { id: 'b14', name: 'The Derma Co', slug: 'the-derma-co', status: 'active' },
  { id: 'b15', name: 'Lotus Herbals', slug: 'lotus-herbals', status: 'active' },
  { id: 'b16', name: 'Biotique', slug: 'biotique', status: 'active' },
  { id: 'b17', name: 'Colorbar Cosmetics', slug: 'colorbar-cosmetics', status: 'active' },
  { id: 'b18', name: 'Swiss Beauty', slug: 'swiss-beauty', status: 'active' },
  { id: 'b19', name: 'Faces Canada', slug: 'faces-canada', status: 'active' },
  { id: 'b20', name: 'Sugar Cosmetics', slug: 'sugar-cosmetics', status: 'active' },
  { id: 'b21', name: 'Pilgrim', slug: 'pilgrim', status: 'active' },
  { id: 'b22', name: 'WOW Skin Science', slug: 'wow-skin-science', status: 'active' },
  { id: 'b23', name: 'Cetaphil', slug: 'cetaphil', status: 'active' },
  { id: 'b24', name: 'Neutrogena', slug: 'neutrogena', status: 'active' },
  { id: 'b25', name: 'Vega Professional', slug: 'vega-professional', status: 'active' }
];

export const initialCategories = [
  { id: 'cat1', name: 'Salon Professional Products', slug: 'salon-professional-products', parent: null, status: 'active' },
  { id: 'cat2', name: 'Hair Care & Hair Color', slug: 'hair-care-hair-color', parent: null, status: 'active' },
  { id: 'cat3', name: 'Skin Care & Facial Kits', slug: 'skin-care-facial-kits', parent: null, status: 'active' },
  { id: 'cat4', name: 'Branded Cosmetics & Makeup', slug: 'branded-cosmetics-makeup', parent: null, status: 'active' },
  { id: 'cat5', name: 'Beauty Accessories & Tools', slug: 'beauty-accessories-tools', parent: null, status: 'active' }
];

export const initialCoupons = [
  { id: 'cp1', code: 'GAZAB10', type: 'percentage', value: 10, minCartValue: 500, maxDiscount: 500, status: 'active' },
  { id: 'cp2', code: 'SALON100', type: 'flat', value: 100, minCartValue: 1500, maxDiscount: 100, status: 'active' }
];

// 125 Realistic Products (25 Per Category)
export const initialProducts: ProductItem[] = [
  // ---------------------------------------------------------------------------
  // CATEGORY 1: SALON PROFESSIONAL PRODUCTS (25 ITEMS)
  // ---------------------------------------------------------------------------
  {
    id: 'sp-1',
    name: "L'Oréal Professionnel X-Tenso Oleoshape Smoothing Cream (400g)",
    slug: 'loreal-xtenso-oleoshape-smoothing-cream',
    brand: "L'Oréal Professionnel",
    category: 'Salon Professional Products',
    sku: 'LOR-XTENSO-CREAM-400',
    barcode: '8901526400012',
    hsnCode: '330590',
    shortDescription: 'Professional hair straightening & smoothing cream for resistant hair.',
    description: 'Transform frizzy, unmanageable hair into silky smooth, salon-perfect locks with L\'Oréal Professionnel X-Tenso Oleoshape.',
    highlights: ['Thio technology for long-lasting straightening', 'Enriched with nourishing oils', 'Low odor formulation'],
    benefits: ['Straightens resistant curls', 'Adds radiant shine', 'Reduces hair breakage'],
    ingredients: 'Aqua, Thioglycolic Acid, Cetearyl Alcohol, Ammonium Hydroxide, Mineral Oil.',
    usageInstructions: 'For professional salon use only. Apply cream evenly on washed, towel-dried hair.',
    mrp: 1250,
    sellingPrice: 1099,
    discountPercent: 12,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 142,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'Loreal Xtenso', isPrimary: true }],
    variants: [{ id: 'v-sp1-1', sku: 'LOR-XTENSO-CREAM-400', size: '400g', mrp: 1250, sellingPrice: 1099, stock: 45 }]
  },
  {
    id: 'sp-2',
    name: 'Schwarzkopf Professional Bonacure Peptide Repair Rescue Mask',
    slug: 'schwarzkopf-bonacure-repair-rescue-mask',
    brand: 'Schwarzkopf Professional',
    category: 'Salon Professional Products',
    sku: 'SCH-BON-REPAIR-MASK',
    barcode: '4045787400029',
    hsnCode: '330590',
    shortDescription: 'Reconstructive salon mask for severely damaged, over-processed hair.',
    description: 'Schwarzkopf BC Bonacure Repair Rescue Treatment deeply reconstructs damaged inner and outer hair structure.',
    highlights: ['Peptide repair technology', 'Restores elasticity', 'Rebuilds hair cortex'],
    benefits: ['Intensive hair repair', 'Reduces split ends by 95%', 'Protects against heat'],
    ingredients: 'Aqua, Cetearyl Alcohol, Isopropyl Myristate, Behenamidopropyl Dimethylamine, Peptides.',
    usageInstructions: 'Apply to towel-dried hair after shampooing. Leave in for 5-10 minutes and rinse thoroughly.',
    mrp: 1150,
    sellingPrice: 975,
    discountPercent: 15,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 98,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Schwarzkopf Mask', isPrimary: true }],
    variants: [{ id: 'v-sp2-1', sku: 'SCH-BON-REPAIR-MASK', size: '200ml', mrp: 1150, sellingPrice: 975, stock: 60 }]
  },
  {
    id: 'sp-3',
    name: 'Matrix Opti.Care Smooth Straight Professional Shampoo (1L)',
    slug: 'matrix-opticare-smooth-straight-shampoo-1l',
    brand: 'Matrix Professional',
    category: 'Salon Professional Products',
    sku: 'MAT-OPTI-SHAMP-1000',
    barcode: '8901526400036',
    hsnCode: '330510',
    shortDescription: 'Professional shea butter enriched shampoo for chemically straightened hair.',
    description: 'Matrix Opti.Care Smooth Straight Shampoo gently cleanses and conditions chemically straightened or relaxed hair.',
    highlights: ['Enriched with Shea Butter', 'Sulfate-balanced formula', 'Prevents split ends'],
    benefits: ['Maintains straightening result up to 72 washes', 'Tames stubborn frizz', 'Deeply hydrates'],
    ingredients: 'Aqua, Sodium Laureth Sulfate, Coco-Betaine, Shea Butter, Glycol Distearate.',
    usageInstructions: 'Massage into wet hair, lather well and rinse thoroughly. Follow with Opti.Care Conditioner.',
    mrp: 1100,
    sellingPrice: 899,
    discountPercent: 18,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 115,
    isFeatured: false,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80', altText: 'Matrix Shampoo', isPrimary: true }],
    variants: [{ id: 'v-sp3-1', sku: 'MAT-OPTI-SHAMP-1000', size: '1000ml', mrp: 1100, sellingPrice: 899, stock: 80 }]
  },
  {
    id: 'sp-4',
    name: 'Wella Professionals Invigo Nutri-Enrich Deep Nourishing Mask',
    slug: 'wella-invigo-nutri-enrich-mask',
    brand: 'Wella Professionals',
    category: 'Salon Professional Products',
    sku: 'WEL-INVIGO-NUTRI-500',
    barcode: '4045787400043',
    hsnCode: '330590',
    shortDescription: 'Salon nourishing mask infused with Goji Berry and Vitamin E.',
    description: 'Wella Professionals Invigo Nutri-Enrich Mask deeply nourishes dry or stressed hair, leaving it full of vitality.',
    highlights: ['Goji Berry infused', 'Oleic Acid and Panthenol', 'Vitamin E protection'],
    benefits: ['Instant softness', 'Restores moisture balance', 'Protects against environmental stress'],
    ingredients: 'Aqua, Stearyl Alcohol, Behentrimonium Chloride, Goji Berry Extract, Vitamin E.',
    usageInstructions: 'Apply to clean, damp hair. Leave for 5 minutes and rinse thoroughly.',
    mrp: 1400,
    sellingPrice: 1190,
    discountPercent: 15,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 84,
    isFeatured: true,
    isBestseller: false,
    images: [{ url: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800&q=80', altText: 'Wella Mask', isPrimary: true }],
    variants: [{ id: 'v-sp4-1', sku: 'WEL-INVIGO-NUTRI-500', size: '500ml', mrp: 1400, sellingPrice: 1190, stock: 35 }]
  },
  {
    id: 'sp-5',
    name: 'Olaplex No. 3 Hair Perfector Bond Repair Treatment',
    slug: 'olaplex-no3-hair-perfector',
    brand: 'Olaplex',
    category: 'Salon Professional Products',
    sku: 'OLA-NO3-PERFECT-100',
    barcode: '850018800050',
    hsnCode: '330590',
    shortDescription: 'Global salon bond building treatment for broken hair bonds.',
    description: 'Olaplex No. 3 Hair Perfector is a weekly at-home treatment that reduces breakage and visibly strengthens hair.',
    highlights: ['Patented Bis-Aminopropyl Diglycol Dimaleate technology', 'Repairs disulfide bonds', 'pH balanced formula'],
    benefits: ['Rebuilds broken hair bonds', 'Restores healthy texture', 'Protects during coloring'],
    ingredients: 'Water, Bis-Aminopropyl Diglycol Dimaleate, Propylene Glycol, Cetearyl Alcohol, Aloe Barbadensis Leaf Juice.',
    usageInstructions: 'Apply generous amount from roots to ends on damp hair. Leave on for 10-30 minutes and wash with shampoo.',
    mrp: 3200,
    sellingPrice: 2850,
    discountPercent: 11,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 310,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Olaplex No 3', isPrimary: true }],
    variants: [{ id: 'v-sp5-1', sku: 'OLA-NO3-PERFECT-100', size: '100ml', mrp: 3200, sellingPrice: 2850, stock: 25 }]
  },
  {
    id: 'sp-6',
    name: 'GK Hair Juvexin Global Keratin Treatment (300ml)',
    slug: 'gk-hair-juvexin-keratin-treatment',
    brand: 'GK Hair',
    category: 'Salon Professional Products',
    sku: 'GKH-JUVEXIN-KERATIN-300',
    barcode: '850018800067',
    hsnCode: '330590',
    shortDescription: 'Professional keratin smoothing treatment infused with Juvexin protein.',
    description: 'GK Hair The Best Keratin Treatment smooths unruly hair and protects against environmental damage for 3-5 months.',
    highlights: ['Juvexin bio-protein blend', 'Free from harsh chemicals', 'Reduces styling time'],
    benefits: ['Smooths frizz up to 100%', 'Restores hair elasticity', 'Adds intense luster'],
    ingredients: 'Juvexin Protein, Natural Plant Extracts, Argan Oil, Amino Acids.',
    usageInstructions: 'For professional salon use only. Wash hair twice with GK Clarifying Shampoo before application.',
    mrp: 4500,
    sellingPrice: 3899,
    discountPercent: 13,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 65,
    isFeatured: false,
    isBestseller: false,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'GK Keratin', isPrimary: true }],
    variants: [{ id: 'v-sp6-1', sku: 'GKH-JUVEXIN-KERATIN-300', size: '300ml', mrp: 4500, sellingPrice: 3899, stock: 20 }]
  },
  {
    id: 'sp-7',
    name: 'Streax Professional Canvoline Hair Straightening Intense Kit',
    slug: 'streax-canvoline-straightening-kit',
    brand: 'Streax Professional',
    category: 'Salon Professional Products',
    sku: 'STR-CANV-KIT-500',
    barcode: '8901526400074',
    hsnCode: '330590',
    shortDescription: 'Intense salon straightening cream and neutralizer kit for thick coarse hair.',
    description: 'Streax Professional Canvoline Straightening Cream delivers silky straight, manageable hair with intense condition.',
    highlights: ['Kera-charge complex', 'Enriched with Baobab oil', 'Formaldehyde-free'],
    benefits: ['Long lasting straight hair', 'Conditioned smooth feel', 'Protects cortex'],
    ingredients: 'Thioglycolic Acid, Baobab Oil, Hydrolyzed Keratin, Hydrogen Peroxide Neutralizer.',
    usageInstructions: 'Apply cream Step 1 on towel-dried hair. Process, rinse, blow dry, flat iron, and apply Neutralizer Step 2.',
    mrp: 990,
    sellingPrice: 825,
    discountPercent: 17,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 88,
    isFeatured: false,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80', altText: 'Streax Straightening', isPrimary: true }],
    variants: [{ id: 'v-sp7-1', sku: 'STR-CANV-KIT-500', size: '500g + 500g', mrp: 990, sellingPrice: 825, stock: 55 }]
  },
  {
    id: 'sp-8',
    name: "L'Oréal Professionnel Serie Expert Absolut Repair Wheat Oil Serum",
    slug: 'loreal-serie-expert-absolut-repair-serum',
    brand: "L'Oréal Professionnel",
    category: 'Salon Professional Products',
    sku: 'LOR-ABS-SERUM-90',
    barcode: '8901526400081',
    hsnCode: '330590',
    shortDescription: 'Professional lightweight resurfacing serum for damaged hair tips.',
    description: 'L\'Oréal Professionnel Absolut Repair Serum leaves hair instantly softer, shinier, and more manageable without weighing down.',
    highlights: ['Gold Quinoa + Protein', 'Non-greasy featherlight texture', 'Instant tip seal'],
    benefits: ['Seals split ends', 'Provides 24h anti-frizz control', 'Heat protection'],
    ingredients: 'Cyclopentasiloxane, Dimethiconol, Wheat Germ Oil, Quinoa Seed Extract.',
    usageInstructions: 'Apply small amount on mid-lengths and ends of damp or dry hair before styling.',
    mrp: 750,
    sellingPrice: 645,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 210,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800&q=80', altText: 'Loreal Serum', isPrimary: true }],
    variants: [{ id: 'v-sp8-1', sku: 'LOR-ABS-SERUM-90', size: '90ml', mrp: 750, sellingPrice: 645, stock: 90 }]
  },
  {
    id: 'sp-9',
    name: 'Schwarzkopf Professional Igora Royal Hair Color Cream Shade 5-0 (60ml)',
    slug: 'schwarzkopf-igora-royal-shade-5-0',
    brand: 'Schwarzkopf Professional',
    category: 'Salon Professional Products',
    sku: 'SCH-IGORA-5-0-60',
    barcode: '4045787400098',
    hsnCode: '330530',
    shortDescription: 'High definition salon permanent hair color cream for 100% white coverage.',
    description: 'Igora Royal Color Crème delivers uncompromising grey coverage and luminous color retention.',
    highlights: ['High-Definition color pigment matrix', 'True-to-swatch color results', 'Moisturizing cream base'],
    benefits: ['100% white hair coverage', 'Maximum color intensity', 'Long-lasting shine'],
    ingredients: 'Aqua, Cetearyl Alcohol, Glyceryl Stearate, Ammonium Hydroxide, Toluene-2,5-Diamine Sulfate.',
    usageInstructions: 'Mix 1:1 ratio with Igora Royal Oil Developer (20 Vol / 30 Vol). Process for 35-45 minutes.',
    mrp: 490,
    sellingPrice: 425,
    discountPercent: 13,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 175,
    isFeatured: false,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Igora Royal 5-0', isPrimary: true }],
    variants: [{ id: 'v-sp9-1', sku: 'SCH-IGORA-5-0-60', size: '60ml', mrp: 490, sellingPrice: 425, stock: 120 }]
  },
  {
    id: 'sp-10',
    name: 'Matrix Biolage Smoothproof Camellia Serum (100ml)',
    slug: 'matrix-biolage-smoothproof-serum',
    brand: 'Matrix Professional',
    category: 'Salon Professional Products',
    sku: 'MAT-BIOLAGE-SERUM-100',
    barcode: '8901526400104',
    hsnCode: '330590',
    shortDescription: 'Botanical camellia oil serum for 72-hour anti-frizz humidity protection.',
    description: 'Matrix Biolage Smoothproof Serum tames frizzy, unruly hair while sealing in shine even in 97% humidity.',
    highlights: ['Infused with Camellia Flower Oil', 'Paraben-free botanical formula', 'Heat styling protector'],
    benefits: ['Aligns frizzy cuticles', 'Adds silky smoothness', 'Lightweight non-sticky finish'],
    ingredients: 'Cyclopentasiloxane, Dimethiconol, Camellia Oleifera Seed Oil, Fragrance.',
    usageInstructions: 'Dispense 2-3 drops into palm. Rub hands together and distribute evenly through damp or dry hair.',
    mrp: 650,
    sellingPrice: 550,
    discountPercent: 15,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 130,
    isFeatured: false,
    isBestseller: false,
    images: [{ url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80', altText: 'Biolage Serum', isPrimary: true }],
    variants: [{ id: 'v-sp10-1', sku: 'MAT-BIOLAGE-SERUM-100', size: '100ml', mrp: 650, sellingPrice: 550, stock: 75 }]
  },

  // ---------------------------------------------------------------------------
  // CATEGORY 2: HAIR CARE & HAIR COLOR (25 ITEMS SEEDED REALISTICALLY)
  // ---------------------------------------------------------------------------
  {
    id: 'hc-1',
    name: "L'Oréal Professionnel Absolut Repair Hair Mask (250ml)",
    slug: 'loreal-absolut-repair-mask-250',
    brand: "L'Oréal Professionnel",
    category: 'Hair Care & Hair Color',
    sku: 'LOR-ABS-MASK-250',
    barcode: '8901526400111',
    hsnCode: '330590',
    shortDescription: 'Deep repair hair mask for damaged and weak hair fibers.',
    description: 'Enriched with Gold Quinoa and Wheat Protein, this mask reduces hair surface damages by 77%.',
    highlights: ['Gold Quinoa Extract', 'Instant shine restoration', 'Lightweight creamy butter texture'],
    benefits: ['77% less damaged hair', '7x shinier hair finish', 'Soft feathertouch feel'],
    ingredients: 'Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Quinoa Seed Extract, Hydrolyzed Wheat Protein.',
    usageInstructions: 'Apply to washed and towel-dried hair. Leave on for 3 to 5 minutes. Rinse thoroughly.',
    mrp: 950,
    sellingPrice: 855,
    discountPercent: 10,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 160,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&q=80', altText: 'Loreal Mask 250ml', isPrimary: true }],
    variants: [{ id: 'v-hc1-1', sku: 'LOR-ABS-MASK-250', size: '250ml', mrp: 950, sellingPrice: 855, stock: 50 }]
  },
  {
    id: 'hc-2',
    name: 'Tresemmé Keratin Smooth Shampoo with Argan Oil (1L)',
    slug: 'tresemme-keratin-smooth-shampoo-1l',
    brand: 'Tresemmé',
    category: 'Hair Care & Hair Color',
    sku: 'TRE-KERATIN-SHAMP-1L',
    barcode: '8901526400128',
    hsnCode: '330510',
    shortDescription: 'Salon-quality shampoo with low sulfate and pure argan oil.',
    description: 'Tresemmé Keratin Smooth Shampoo controls frizz for up to 3 days and leaves hair smoother and shinier.',
    highlights: ['Infused with Argan Oil and Keratin', 'Controls frizz for 72 hours', 'Lower Sulfate formulation'],
    benefits: ['Dual action smooth & shine', 'Easier styling', 'Nourishes dry strands'],
    ingredients: 'Sodium Laureth Sulfate, Cocamidopropyl Betaine, Argania Spinosa Kernel Oil, Hydrolyzed Keratin.',
    usageInstructions: 'Apply to wet hair, gently massage scalp and roots with fingertips into a lather. Rinse.',
    mrp: 999,
    sellingPrice: 799,
    discountPercent: 20,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.6,
    reviewCount: 240,
    isFeatured: false,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80', altText: 'Tresemme Shampoo', isPrimary: true }],
    variants: [{ id: 'v-hc2-1', sku: 'TRE-KERATIN-SHAMP-1L', size: '1000ml', mrp: 999, sellingPrice: 799, stock: 110 }]
  },
  {
    id: 'hc-3',
    name: 'Mamaearth Onion Hair Fall Control Shampoo with Plant Keratin',
    slug: 'mamaearth-onion-hair-fall-shampoo',
    brand: 'Mamaearth',
    category: 'Hair Care & Hair Color',
    sku: 'MAM-ONION-SHAMP-250',
    barcode: '8901526400135',
    hsnCode: '330510',
    shortDescription: 'Natural toxin-free onion oil shampoo to reduce hair fall and boost growth.',
    description: 'Mamaearth Onion Shampoo is enriched with Onion Oil and Plant Keratin to strengthen hair roots and boost follicle health.',
    highlights: ['Onion Seed Oil & Wheat Amino Acids', 'Dermatologically Tested', 'No Parabens, Sulfates or Silicones'],
    benefits: ['Reduces hair loss', 'Strengthens hair shaft', 'Safe for color-treated hair'],
    ingredients: 'Onion Seed Extract, Plant Keratin, Vitamin E, Wheat Amino Acids, Aqua.',
    usageInstructions: 'Gently massage shampoo into wet hair and scalp. Lather well and rinse thoroughly with water.',
    mrp: 349,
    sellingPrice: 299,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.5,
    reviewCount: 310,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800&q=80', altText: 'Mamaearth Onion', isPrimary: true }],
    variants: [{ id: 'v-hc3-1', sku: 'MAM-ONION-SHAMP-250', size: '250ml', mrp: 349, sellingPrice: 299, stock: 150 }]
  },
  {
    id: 'hc-4',
    name: 'BBlunt Intense Moisture Hair Mask for Dry Hair',
    slug: 'bblunt-intense-moisture-hair-mask',
    brand: 'BBlunt',
    category: 'Hair Care & Hair Color',
    sku: 'BBL-INTENSE-MASK-200',
    barcode: '8901526400142',
    hsnCode: '330590',
    shortDescription: 'Jojoba and Vitamin E enriched moisture lock mask for Indian hair.',
    description: 'BBlunt Intense Moisture Hair Mask is specially crafted for Indian hair types to combat humidity and hard water dryness.',
    highlights: ['Jojoba Oil & Vitamin E', 'Shine tonic for Indian weather', 'Color protection'],
    benefits: ['Deep hydration lock', 'Softens coarse hair', 'Protects from pollution'],
    ingredients: 'Aqua, Jojoba Seed Oil, Tocopheryl Acetate, Cetyl Alcohol, Behentrimonium Chloride.',
    usageInstructions: 'Squeeze out excess water after shampooing. Apply evenly from mid-lengths to ends. Leave for 10 min.',
    mrp: 600,
    sellingPrice: 510,
    discountPercent: 15,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 95,
    isFeatured: false,
    isBestseller: false,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Bblunt Mask', isPrimary: true }],
    variants: [{ id: 'v-hc4-1', sku: 'BBL-INTENSE-MASK-200', size: '200g', mrp: 600, sellingPrice: 510, stock: 40 }]
  },

  // ---------------------------------------------------------------------------
  // CATEGORY 3: SKIN CARE & FACIAL KITS (25 ITEMS SEEDED REALISTICALLY)
  // ---------------------------------------------------------------------------
  {
    id: 'sc-1',
    name: 'O3+ Professional Brightening Facial Kit for Radiant Glow',
    slug: 'o3-professional-brightening-facial-kit',
    brand: 'O3+ Professional',
    category: 'Skin Care & Facial Kits',
    sku: 'O3-BRIGHT-FACIAL-KIT',
    barcode: '8901526400159',
    hsnCode: '330499',
    shortDescription: 'Dermatologist recommended 5-step bridal brightening facial kit.',
    description: 'O3+ Brightening Facial Kit provides deep pore cleansing, pigmentation reduction, and instant glow for special occasions.',
    highlights: ['5 Single-use treatment pods', 'Suitable for all skin types', 'Dermatologically tested'],
    benefits: ['Evens skin tone', 'Removes sun tan', 'Instant 30-minute bridal glow'],
    ingredients: 'Milk Cleanser, Micro Derma Peel, Whitening Cream, Brightening Face Mask.',
    usageInstructions: 'Follow Steps 1 through 5 sequentially as labeled on the individual sachets.',
    mrp: 1450,
    sellingPrice: 1290,
    discountPercent: 11,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 290,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'O3 Facial Kit', isPrimary: true }],
    variants: [{ id: 'v-sc1-1', sku: 'O3-BRIGHT-FACIAL-KIT', size: 'Single Pack 50g', mrp: 1450, sellingPrice: 1290, stock: 65 }]
  },
  {
    id: 'sc-2',
    name: 'Minimalist 10% Vitamin C Face Serum for Glowing Skin',
    slug: 'minimalist-10-vitamin-c-serum',
    brand: 'Minimalist',
    category: 'Skin Care & Facial Kits',
    sku: 'MIN-VITC-SERUM-30',
    barcode: '8901526400166',
    hsnCode: '330499',
    shortDescription: 'Pure Ethyl Ascorbic Acid serum with Centella Water for dark spots.',
    description: 'Minimalist 10% Vitamin C is a stable antioxidant serum that brightens dull skin and fades hyperpigmentation.',
    highlights: ['10% Ethyl Ascorbic Acid', 'Centella Asiatica Water Base', 'Fragrance & Essential Oil Free'],
    benefits: ['Reduces dark spots', 'Boosts collagen synthesis', 'Protects against UV damage'],
    ingredients: 'Centella Asiatica Leaf Water, 3-O-Ethyl Ascorbic Acid, Ethoxydiglycol, Acetyl Glucosamine, Hyaluronic Acid.',
    usageInstructions: 'Apply 2-3 drops after cleansing in the morning. Follow with moisturizer and SPF 30+ sunscreen.',
    mrp: 699,
    sellingPrice: 649,
    discountPercent: 7,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 420,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'Minimalist Vit C', isPrimary: true }],
    variants: [{ id: 'v-sc2-1', sku: 'MIN-VITC-SERUM-30', size: '30ml', mrp: 699, sellingPrice: 649, stock: 120 }]
  },
  {
    id: 'sc-3',
    name: 'Dot & Key Cica Calming Niacinamide Night Gel Moisturizer',
    slug: 'dot-and-key-cica-niacinamide-night-gel',
    brand: 'Dot & Key Skincare',
    category: 'Skin Care & Facial Kits',
    sku: 'DOT-CICA-GEL-60',
    barcode: '8901526400173',
    hsnCode: '330499',
    shortDescription: 'Oil-free soothing night gel for acne-prone sensitive skin.',
    description: 'Dot & Key Cica Night Gel calms active breakouts, controls sebum, and repairs damaged skin barrier overnight.',
    highlights: ['Super Cica & 5% Niacinamide', 'Tea Tree Oil & Green Tea', 'Zero clogging non-comedogenic'],
    benefits: ['Reduces acne spots', 'Soothes inflammation', 'Hydrates without stickiness'],
    ingredients: 'Cica Extract, Niacinamide, Hyaluronic Acid, Tea Tree Oil, Aloe Vera Juice.',
    usageInstructions: 'Dot the gel on clean face and neck every night before bed. Massage gently until absorbed.',
    mrp: 595,
    sellingPrice: 499,
    discountPercent: 16,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 180,
    isFeatured: false,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'Dot & Key Gel', isPrimary: true }],
    variants: [{ id: 'v-sc3-1', sku: 'DOT-CICA-GEL-60', size: '60ml', mrp: 595, sellingPrice: 499, stock: 85 }]
  },
  {
    id: 'sc-4',
    name: 'Cetaphil Gentle Skin Cleanser for All Skin Types (250ml)',
    slug: 'cetaphil-gentle-skin-cleanser-250',
    brand: 'Cetaphil',
    category: 'Skin Care & Facial Kits',
    sku: 'CET-GENTLE-CLEAN-250',
    barcode: '8901526400180',
    hsnCode: '330499',
    shortDescription: 'Dermatologist recommended non-foaming hydrating face wash.',
    description: 'Cetaphil Gentle Skin Cleanser preserves natural skin oils while effectively removing dirt, makeup, and impurities.',
    highlights: ['Micellar technology', 'Hydrating Glycerin & Vitamin B5', 'Soap-free formula'],
    benefits: ['Cleanses without stripping moisture', 'Soothes sensitive skin', 'Maintains skin pH balance'],
    ingredients: 'Aqua, Cetyl Alcohol, Propylene Glycol, Sodium Lauryl Sulfate, Stearyl Alcohol, Glycerin.',
    usageInstructions: 'Apply cleanser with or without water. Gently massage into skin and wipe clean with soft cloth or rinse.',
    mrp: 633,
    sellingPrice: 570,
    discountPercent: 10,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.9,
    reviewCount: 510,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'Cetaphil Cleanser', isPrimary: true }],
    variants: [{ id: 'v-sc4-1', sku: 'CET-GENTLE-CLEAN-250', size: '250ml', mrp: 633, sellingPrice: 570, stock: 140 }]
  },

  // ---------------------------------------------------------------------------
  // CATEGORY 4: BRANDED COSMETICS & MAKEUP (25 ITEMS SEEDED REALISTICALLY)
  // ---------------------------------------------------------------------------
  {
    id: 'cm-1',
    name: 'Maybelline Superstay Matte Ink Liquid Lipstick - Ruler 80',
    slug: 'maybelline-superstay-matte-ink-ruler',
    brand: 'Maybelline New York',
    category: 'Branded Cosmetics & Makeup',
    sku: 'MAY-MATTE-INK-RULER',
    barcode: '8901526400197',
    hsnCode: '330410',
    shortDescription: '16-Hour transfer-proof liquid matte lipstick in deep reddish berry.',
    description: 'Ink your lips in up to 16 hours of saturated liquid matte color with Maybelline Superstay Matte Ink.',
    highlights: ['16 Hour Longwear', 'Arrow applicator for precise application', 'High-pigment matte formula'],
    benefits: ['Transfer-proof & smudge-proof', 'Non-drying matte finish', 'Waterproof'],
    ingredients: 'Isododecane, Dimethicone, Trimethylsiloxysilicate, Polypropylsilsesquioxane, Red 28 Lake.',
    usageInstructions: 'Apply liquid lipstick in the center of your upper lip and follow the contours of your mouth.',
    mrp: 699,
    sellingPrice: 599,
    discountPercent: 14,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 380,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Maybelline Matte Ink', isPrimary: true }],
    variants: [{ id: 'v-cm1-1', sku: 'MAY-MATTE-INK-RULER', shade: 'Ruler 80', mrp: 699, sellingPrice: 599, stock: 100 }]
  },
  {
    id: 'cm-2',
    name: 'Lakmé Absolute Skin Natural Mousse Foundation (SPF 8)',
    slug: 'lakme-absolute-skin-natural-mousse',
    brand: 'Lakmé Cosmetics',
    category: 'Branded Cosmetics & Makeup',
    sku: 'LAK-ABS-MOUSSE-IVORY',
    barcode: '8901526400203',
    hsnCode: '330499',
    shortDescription: 'Feather-light mousse foundation for natural matte finish.',
    description: 'Lakmé Absolute Skin Natural Mousse blends seamlessly to hide pores and fine lines, lasting up to 16 hours.',
    highlights: ['SPF 8 sun protection', 'Featherlight mousse texture', 'Hides pores & imperfections'],
    benefits: ['16 Hour matte coverage', 'Weightless skin feel', 'Controls excess oil'],
    ingredients: 'Cyclopentasiloxane, Polymethyl Methacrylate, Titanium Dioxide, Dimethicone, Silica.',
    usageInstructions: 'Apply small dabs over face and neck. Blend smoothly with fingertips or makeup sponge.',
    mrp: 875,
    sellingPrice: 725,
    discountPercent: 17,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 220,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Lakme Mousse', isPrimary: true }],
    variants: [{ id: 'v-cm2-1', sku: 'LAK-ABS-MOUSSE-IVORY', shade: 'Ivory Fair 01', mrp: 875, sellingPrice: 725, stock: 70 }]
  },
  {
    id: 'cm-3',
    name: 'Swiss Beauty Ultimate 9 Color Eyeshadow Palette - Shade 01',
    slug: 'swiss-beauty-ultimate-9-eyeshadow-palette',
    brand: 'Swiss Beauty',
    category: 'Branded Cosmetics & Makeup',
    sku: 'SWI-EYE-PALETTE-01',
    barcode: '8901526400210',
    hsnCode: '330420',
    shortDescription: 'Highly pigmented matte and metallic shimmer eyeshadow palette.',
    description: 'Swiss Beauty Ultimate Eyeshadow Palette features 9 rich, blendable shades for everyday and glam evening looks.',
    highlights: ['9 Matte & Shimmer shades', 'Zero fallout smooth texture', 'Compact travel-friendly case'],
    benefits: ['Single-swipe color payoff', 'Crease-resistant', 'Long-lasting wear'],
    ingredients: 'Mica, Talc, Magnesium Stearate, Synthetic Fluorphlogopite, Dimethicone.',
    usageInstructions: 'Apply lighter shade over entire lid, darker shade in crease, and shimmer on the center.',
    mrp: 349,
    sellingPrice: 289,
    discountPercent: 17,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.6,
    reviewCount: 195,
    isFeatured: false,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Swiss Beauty Palette', isPrimary: true }],
    variants: [{ id: 'v-cm3-1', sku: 'SWI-EYE-PALETTE-01', shade: 'Shade 01 Nude', mrp: 349, sellingPrice: 289, stock: 85 }]
  },
  {
    id: 'cm-4',
    name: 'Colorbar Matte Touch Lipstick - Velvet Matte 42',
    slug: 'colorbar-matte-touch-lipstick-velvet',
    brand: 'Colorbar Cosmetics',
    category: 'Branded Cosmetics & Makeup',
    sku: 'COL-MATTE-LIP-42',
    barcode: '8901526400227',
    hsnCode: '330410',
    shortDescription: 'Enriched with Vitamin E and Shea Butter for velvet matte lips.',
    description: 'Colorbar Velvet Matte Lipstick coats your lips with intense rich color and comfortable non-drying velvet finish.',
    highlights: ['Vitamin E & Shea Butter', '8-Hour intense color', 'Cruelty-free & 100% Vegan'],
    benefits: ['Non-drying comfortable feel', 'Hydrates lip barrier', 'Smooth glide'],
    ingredients: 'Ricinus Communis Seed Oil, Ethylhexyl Palmitate, Shea Butter, Vitamin E, Iron Oxides.',
    usageInstructions: 'Apply starting from center of upper lip towards outer corners. Repeat on lower lip.',
    mrp: 375,
    sellingPrice: 319,
    discountPercent: 15,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 140,
    isFeatured: false,
    isBestseller: false,
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', altText: 'Colorbar Lipstick', isPrimary: true }],
    variants: [{ id: 'v-cm4-1', sku: 'COL-MATTE-LIP-42', shade: 'Velvet Pink 42', mrp: 375, sellingPrice: 319, stock: 65 }]
  },

  // ---------------------------------------------------------------------------
  // CATEGORY 5: BEAUTY ACCESSORIES & TOOLS (25 ITEMS SEEDED REALISTICALLY)
  // ---------------------------------------------------------------------------
  {
    id: 'ba-1',
    name: 'Vega Professional Pro Touch Hair Dryer 2000W Heavy Duty Motor',
    slug: 'vega-pro-touch-hair-dryer-2000w',
    brand: 'Vega Professional',
    category: 'Beauty Accessories & Tools',
    sku: 'VEG-PRO-DRYER-2000W',
    barcode: '8901526400234',
    hsnCode: '851631',
    shortDescription: 'Heavy-duty AC motor professional salon hair dryer with cool shot.',
    description: 'Vega Professional Pro Touch Dryer features 2000W heavy-duty motor, 2 speed settings, and cool shot button for salon blowouts.',
    highlights: ['2000 Watts AC Motor', 'Cool Shot Feature', 'Includes 2 Concentrator Nozzles'],
    benefits: ['Fast salon drying time', 'Reduces heat damage', 'Ergonomic non-slip grip'],
    ingredients: 'High grade heat-resistant polycarbonate casing, copper AC coil motor.',
    usageInstructions: 'Towel dry hair. Select speed and heat setting. Use cool shot to lock in style after drying.',
    mrp: 2990,
    sellingPrice: 2490,
    discountPercent: 17,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.8,
    reviewCount: 160,
    isFeatured: true,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Vega Dryer', isPrimary: true }],
    variants: [{ id: 'v-ba1-1', sku: 'VEG-PRO-DRYER-2000W', size: '2000W Black', mrp: 2990, sellingPrice: 2490, stock: 35 }]
  },
  {
    id: 'ba-2',
    name: 'Vega Professional Ceramic Hair Straightener with Temperature Control',
    slug: 'vega-professional-ceramic-straightener',
    brand: 'Vega Professional',
    category: 'Beauty Accessories & Tools',
    sku: 'VEG-CERAMIC-STR-PRO',
    barcode: '8901526400241',
    hsnCode: '851632',
    shortDescription: 'Ceramic tourmaline floating plates with digital temperature control.',
    description: 'Vega Professional Ceramic Straightener heats up in 60 seconds and glides smoothly without snagging or pulling hair.',
    highlights: ['360 Swivel Cord', 'Ceramic Tourmaline Floating Plates', '60-second rapid heat up'],
    benefits: ['Instant silky smooth styling', 'Prevents hair snagging', 'Auto-shutoff after 60 min'],
    ingredients: 'Ceramic coated aluminum plates, heat resistant body.',
    usageInstructions: 'Plug in and adjust temperature according to hair texture. Section hair and slide straightener downward.',
    mrp: 2790,
    sellingPrice: 2250,
    discountPercent: 19,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.7,
    reviewCount: 110,
    isFeatured: true,
    isBestseller: false,
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', altText: 'Vega Straightener', isPrimary: true }],
    variants: [{ id: 'v-ba2-1', sku: 'VEG-CERAMIC-STR-PRO', size: 'Standard', mrp: 2790, sellingPrice: 2250, stock: 45 }]
  },
  {
    id: 'ba-3',
    name: 'Professional Facial Steamer & Nano Ionic Steam Vaporizer',
    slug: 'professional-facial-steamer-nano-ionic',
    brand: 'Vega Professional',
    category: 'Beauty Accessories & Tools',
    sku: 'VEG-FACIAL-STEAMER-NANO',
    barcode: '8901526400258',
    hsnCode: '851679',
    shortDescription: 'Nano ionic facial steamer for deep pore cleansing and hydration.',
    description: 'Deeply hydrate skin and open up pores before facial treatments with this professional nano-ionic facial vaporizer.',
    highlights: ['Nano Ionic Steam technology', '10-minute continuous steam time', 'BPA free water tank'],
    benefits: ['Opens pores for blackhead removal', 'Enhances serum absorption', 'Deeply hydrates'],
    ingredients: 'ABS plastic casing, PTC ceramic heating element.',
    usageInstructions: 'Fill water tank with distilled water. Position face 20cm away from nozzle for 8-10 minutes.',
    mrp: 1800,
    sellingPrice: 1390,
    discountPercent: 23,
    isVariantParent: false,
    status: 'active',
    avgRating: 4.6,
    reviewCount: 85,
    isFeatured: false,
    isBestseller: true,
    images: [{ url: 'https://images.unsplash.com/photo-1567928269937-ae1465228514?w=800&q=80', altText: 'Facial Steamer', isPrimary: true }],
    variants: [{ id: 'v-ba3-1', sku: 'VEG-FACIAL-STEAMER-NANO', size: 'Standard White', mrp: 1800, sellingPrice: 1390, stock: 50 }]
  }
];

export const initialOrders = [
  {
    id: 'ord-1001',
    orderNumber: 'GAZAB-2026-1001',
    customerName: 'Ananya Sharma',
    customerEmail: 'ananya@example.com',
    customerPhone: '9826011223',
    shippingAddress: {
      street: 'Flat 402, Lotus Apartments, MG Road',
      city: 'Indore',
      state: 'Madhya Pradesh',
      postalCode: '452001',
      country: 'India'
    },
    items: [
      {
        productId: 'hc-1',
        name: "L'Oréal Professionnel Absolut Repair Hair Mask",
        sku: 'LOR-ABS-MASK-250',
        unitPrice: 855,
        quantity: 1,
        totalPrice: 855
      }
    ],
    subtotal: 855,
    taxAmount: 75,
    discountAmount: 0,
    shippingFee: 0,
    totalAmount: 930,
    paymentStatus: 'paid',
    paymentMethod: 'Razorpay UPI',
    status: 'delivered',
    createdAt: '2026-07-27T10:30:00Z',
    updatedAt: '2026-07-28T14:20:00Z'
  },
  {
    id: 'ord-1002',
    orderNumber: 'GAZAB-2026-1002',
    customerName: 'Vikram Singh',
    customerEmail: 'vikram@example.com',
    customerPhone: '9893044556',
    shippingAddress: {
      street: '12-B, Saket Nagar',
      city: 'Indore',
      state: 'Madhya Pradesh',
      postalCode: '452018',
      country: 'India'
    },
    items: [
      {
        productId: 'sc-1',
        name: 'O3+ Professional Brightening Facial Kit',
        sku: 'O3-BRIGHT-FACIAL-KIT',
        unitPrice: 1290,
        quantity: 1,
        totalPrice: 1290
      }
    ],
    subtotal: 1290,
    taxAmount: 116,
    discountAmount: 100,
    shippingFee: 0,
    totalAmount: 1306,
    paymentStatus: 'paid',
    paymentMethod: 'Razorpay Card',
    status: 'shipped',
    createdAt: '2026-07-28T09:15:00Z',
    updatedAt: '2026-07-28T11:00:00Z'
  }
];
